
interface ExportData {
  bookTitle: string;
  reportDate: string;
  totalViews: number;
  uniqueVisitors: number;
  downloads: number;
  totalReadingTime: number;
  averageReadingTime: number;
  completionRate: number;
  shares: number;
  clicks: number;
  revenue: number;
  topPages: Array<{
    page: string;
    views: number;
    avgTime: string;
  }>;
  demographics: Array<{
    name: string;
    value: number;
  }>;
}

export function exportAnalyticsReport(data: ExportData) {
  const report = generateReportContent(data);
  downloadReport(report, `${data.bookTitle}_Analytics_Report.txt`);
}

function generateReportContent(data: ExportData): string {
  return `
==============================================
📊 BOOK ANALYTICS REPORT
==============================================

Book: ${data.bookTitle}
Report Generated: ${data.reportDate}

==============================================
📈 KEY METRICS
==============================================

Total Views: ${data.totalViews.toLocaleString()}
Unique Visitors: ${data.uniqueVisitors.toLocaleString()}
Downloads: ${data.downloads}
Total Reading Time: ${data.totalReadingTime} hours
Average Session Time: ${data.averageReadingTime} minutes
Completion Rate: ${data.completionRate}%
Social Shares: ${data.shares}
Link Clicks: ${data.clicks}
Revenue: $${data.revenue.toFixed(2)}

==============================================
📖 TOP PERFORMING PAGES
==============================================

${data.topPages.map((page, index) => 
  `${index + 1}. ${page.page}
     Views: ${page.views}
     Avg. Time: ${page.avgTime}
`).join('\n')}

==============================================
📱 DEVICE USAGE
==============================================

${data.demographics.map(item => 
  `${item.name}: ${item.value}%`
).join('\n')}

==============================================
🎯 INSIGHTS & RECOMMENDATIONS
==============================================

• Completion Rate Analysis: ${data.completionRate > 60 ? 'Excellent engagement - readers are finishing your book!' : 'Consider optimizing content structure for better retention.'}

• Device Optimization: ${data.demographics.find(d => d.name === 'Mobile')?.value > 60 ? 'Prioritize mobile reading experience optimization.' : 'Desktop users are your primary audience.'}

• Reading Time: ${data.averageReadingTime > 30 ? 'Strong session engagement detected.' : 'Consider shorter chapters or more engaging content to increase session time.'}

• Social Performance: ${data.shares > 50 ? 'Great social traction - leverage this with more sharing incentives.' : 'Implement social sharing prompts to increase visibility.'}

==============================================
Report generated by Million Dollar eBooks
${new Date().toISOString()}
==============================================
  `.trim();
}

function downloadReport(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
