// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnbnldbiqzzbxudcjynv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYm5sZGJpcXp6Ynh1ZGNqeW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTMwNjksImV4cCI6MjA2NDI4OTA2OX0.uBPOW9fmQHVLNSmFHyEQxoKpWrMi-fWiBajYteTEnpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);